### ISSUE TITLE
Implement registration_endpoint

### ISSUE THREAD

**Issue by pizzamaker** [hannesmannerheim/qvitter#338]
Not sure if this is the correct repo for this bug, but whenever I try to follow a user on identi.ca, I get this error:

    Error: quitter.se does not implement registration_endpoint
        at Function.<anonymous> (/opt/pump.io/lib/model/host.js:151:30)
        at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
        at Function.<anonymous> (/opt/pump.io/node_modules/webfinger/lib/webfinger.js:352:17)
        at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
        at jrd (/opt/pump.io/node_modules/webfinger/lib/webfinger.js:159:9)
        at IncomingMessage.<anonymous> (/opt/pump.io/node_modules/webfinger/lib/webfinger.js:230:13)
        at IncomingMessage.EventEmitter.emit (events.js:117:20)
        at _stream_readable.js:920:16
        at process._tickCallback (node.js:415:13)

**Comment by hannesmannerheim** [comment]
i don't fully understand. i think this is a gnu social issue, but gnu social is not compatible with pump

**Comment by hannesmannerheim** [comment]
gnu social issue tracker: https://git.gnu.io/gnu/gnu-social
